language: node_js
node_js:
  - "6"
  - "node"
before_install:
  - openssl aes-256-cbc -K $encrypted_3bdfd4c9bdba_key -iv $encrypted_3bdfd4c9bdba_iv -in secrets.ini.enc -out settings\secrets.ini -d
  - npm install -g gulp
install: npm install
script: npm test
