module.exports = {
  'AG': '#4286f4', // CORRIENTES Y SUPERFICIES DE AGUA
  'CA': 'no_use_defined', // VIALES
  'CF': '#faff00', // ASOCIACIÓN CÍTRICOS-FRUTALES
  'CI': '#ff5d00', // CITRICOS
  'CO': '#447200', // CONTORNO OLIVAR
  'CS': '#594b00', // ASOCIACIÓN CÍTRICOS-FRUTALES DE CÁSCARA
  'CV': '#840158', // ASOCIACIÓN CÍTRICOS-VIÑEDO
  'ED': '#000000', // EDIFICACIONES
  'FF': '#8c5804', // ASOCIACIÓN FRUTALES-FRUTALES DE CÁSCARA
  'FL': '#8e7245', // FRUTOS SECOS Y OLIVAR
  'FO': '#578e45', // FORESTAL
  'FS': '#dbb467', // FRUTOS SECOS
  'FV': '#f99def', // FRUTOS SECOS Y VIÑEDO
  'FY': '#ad2e54', // FRUTALES
  'IM': '#ffffff', // IMPRODUCTIVOS
  'IS': '#ffe187', // ISLAS
  'IV': '#6c92b2', // INVERNADEROS Y CULTIVOS BAJO PLASTICO
  'OC': '#a6db34', // ASOCIACIÓN OLIVAR-CÍTRICOS
  'OF': '#78a023', // OLIVAR -  FRUTAL
  'OV': '#395400', // OLIVAR
  'PA': '#ffcd2b', // PASTO CON ARBOLADO
  'PR': '#d8ff2a', // PASTO ARBUSTIVO
  'PS': '#9cf904', // PASTIZAL
  'TA': '#f9ec03', // TIERRAS ARABLES
  'TH': '#3d9e3f', // HUERTA
  'VF': '#893e93', // VIÑEDO - FRUTAL
  'VI': '#9542f4', // VIÑEDO
  'VO': '#9043d8', // VIÑEDO - OLIVAR
  'ZC': '#cc5151', // ZONA CONCENTRADA NO INCLUIDA EN LA ORTOFOTO
  'ZU': '#770000', // ZONA URBANA
  'ZV': '#ff0000', // ZONA CENSURADA
  'FRUTALES SECANO': '#03f98a',
  'IMPRODUCTIVO': '#03d4f9',
  'LABOR O LABRADÍO SECANO': '#f9ec03',
  'LABOR O LABRADÍO REGADÍO': '#602e04',
  'MONTE BAJO': '#0e771f',
  'PASTOS': '#ffe39e',
  'PRADOS O PRADERAS': '#9cf904',
  'ROBLEDAL': '#f9ab03',
  'VIÑA SECANO': '#9542f4',
  'no_use_defined': '#ffffff'
}
