module.exports = {
  'meet-open-smart-country': 'Meet Open Smart Country',
  'contact': 'Contact',
  'go-to-osc': 'Go to Open Smart Country',
  'landing-claim': 'Make your plot useful and sustainable',
  'upload-your-plot': 'Upload your Plot',
  'upload-your-plot-explanation': 'OSC starts your with a free plot profile, so you can get all open data of your plot with just one click. Keep your plot profile online.',
  'anywhere-plot': 'See your plot profile anywhere',
  'anywhere-plot-explanation': 'You plot profile in OSC can be reached from any smartphone, tablet or computer. So wherever you go, your plot profile follow.',
  'share-your-plot': 'Share your plot information',
  'share-your-plot-explanation': 'You can quickly invite others to view, donwload and share your plot profile. Great things happen when people collaborate. You can easily download a report for email attachment or whatever you want.',
  'get-started': 'Get started with Open Smart Country for free',
  'languaje': 'Languaje',
  'spanish': 'Spanish',
  'english': 'English',
  'signin': 'Sign in',
  'search-osc': 'Search Open Smart Country',
  'save': 'Save',
  'nearby-plots': 'Nearby plots',
  'download': 'Download report',
  'share': 'Share'
}
