module.exports = {
  'meet-open-smart-country': 'Descubre Open Smart Country',
  'contact': 'Contacto',
  'go-to-osc': 'Ir a Open Smart Country',
  'landing-claim': 'Tu parcela útil y sostenible',
  'upload-your-plot': 'Pon tu parcela online',
  'upload-your-plot-explanation': 'OSC te ofrece un perfil de tu parcela gratuito. Pon tu parcela online, hoy si algo no está en internet no existe. Añade información de interés y comparte en tus redes sociales.',
  'anywhere-plot': 'La información de tu parcela desde cualquier lugar',
  'anywhere-plot-explanation': 'Puedes acceder a la información de tu parcela desde cualquier smartphone, tablet u ordenador. Estés dondes estés tu información estará contigo.',
  'share-your-plot': 'Comparte la información de tu parcela',
  'share-your-plot-explanation': 'Puedes enviar fácilmente a otros usuarios la información de tu parcela, también puedes descargar un informe para enviar cómodamente o para incluir junto a otro tipo de información.',
  'get-started': 'Empieza a usar Open Smart Country gratis',
  'languaje': 'Idioma',
  'spanish': 'Español',
  'english': 'Inglés',
  'signin': 'Iniciar sesión',
  'search-osc': 'Buscar en Open Smart Country',
  'save': 'Guardar',
  'nearby-plots': 'Parcelas cercanas',
  'download': 'Descargar informe',
  'share': 'Compartir',
  'suggest-an-edit': 'Sugerir un cambio',
  'claim-plot': 'Reclamar esta parcela',
  'area': 'Superficie catastral {squareMeters, number} m\xB2',
  'altitude': 'Altitud media {meters, number} m'
}
